In [16]:
import numpy as np

### Scalars, Vectors, Matrices and Tensors

In [2]:
# Scalars
scalar = 2
scalar

2

In [3]:
# Vectors
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [4]:
# Matrices
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Checking the shape of a matrix/vector
matrix.shape

(3, 3)

In [6]:
# Tensors
import tensorflow as tf

In [8]:
tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

### Operations on matrices

In [9]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [10]:
# Multiplication
np.dot(A,B)

array([[ 6,  6,  6],
       [15, 15, 15],
       [24, 24, 24]])

In [11]:
# Transposition
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
# Addition
S = A + B
S

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Norms

In [25]:
from numpy.linalg import norm

In [26]:
# L1 norm
a = np.array([1,2,3])
l1 = norm(a,1)
l1

6.0

In [28]:
# L2 norm
l2 = norm(a)
l2

3.7416573867739413